#!/usr/bin/env node
try {
    require('child_process').execSync("tsc generator.ts");
} catch (e) {
    console.log("TypeScript compilation error:");
    console.log(e.stdout.toString());
    process.exit(1);
}
require('./generator.js');